#pragma once

#include "AKeyable.h"
#include "IJsonable.h"

#include "CRecipeItem.h"

#include "types/CRecipe.h"

namespace ypp_sm
{

/**
 * @brief Class for a recipe.
 */
class CRecipe : public IJsonable, public AKeyable
{
protected:
	using items = types::CRecipe::items;
	using count = types::CRecipeItem::count;

public:
	/**
	 * @brief Member constructor.
	 * @param aName Name of the recipe.
	 * @param aItems \copybrief mItems
	 * @param aYield \copybrief mYield
	 */
	explicit CRecipe( std::string_view aName, const items& aItems, count aYield = 1 );

	/**
	 * @brief JSON constructor.
	 * @param aJSON JSON object
	 * @param aName Name of the item.
	 */
	explicit CRecipe( const json& aJSON, std::string_view aName );

protected:
	/**
	 * @copydoc IJsonable::ToJSON
	 */
	void JSON( json& aJSON ) const noexcept override;

public:
	//! Retrieves the \copybrief mItems
	const items& GetItems() const noexcept;

	//! Retrieves the \copybrief mYield
	count GetYield() const noexcept;

private:
	//! Items needed for the recipe.
	items mItems;
	//! Items generated by the recipe.
	count mYield;
};

} // ypp_sm namespace
