#pragma once

#include "AKeyable.h"
#include "IDescriptable.h"
#include "IJsonable.h"

#include "traits/CRecipe.h"
#include "types/CPricesTable.h"
#include "types/CRecipe.h"

namespace ypp_sm
{

/**
 * @brief Class for a recipe.
 */
class CRecipe : public IJsonable, public IDescriptable, public AKeyable, protected json_traits<CRecipe>, protected default_traits<CRecipe>
{
protected:
	using items = types::CRecipe::items;
	using count = types::CRecipe::count;
	using int_price = types::CPricesTable::int_price;

public:
	/**
	 * @brief Member constructor.
	 * @param aName Name of the recipe.
	 * @param aItems \copybrief mItems
	 * @param aDoubloonCount \copybrief mDoubloonCount
	 * @param aYield \copybrief mYield
	 * @param aPriceAdjustment \copybrief mPriceAdjustment
	 */
	explicit CRecipe( std::string_view aName,
			const items& aItems,
			count aDoubloonCount = 0,
			count aYield = DEFAULT_YIELD,
			int_price aPriceAdjustment = 0 );

	/**
	 * @brief JSON constructor.
	 * @param aJSON JSON object
	 * @param aName Name of the item.
	 */
	explicit CRecipe( const json& aJSON, std::string_view aName );

protected:
	/**
	 * @copydoc IJsonable::ToJSON
	 */
	void JSON( json& aJSON ) const noexcept override;

private:
	/**
	 * @copydoc IJsonable::ToJSON
	 */
	std::string Description( unsigned int aIndentDepth, char aIndentChar ) const noexcept override;

public:
	//! Retrieves the \copybrief mItems
	const items& GetItems() const noexcept;

	//! Retrieves the \copybrief mYield
	count GetYield() const noexcept;

	//! Retrieves the \copybrief mDoubloonCount
	count GetDoubloonCount() const noexcept;

	//! Retrieves the \copybrief mPriceAdjustment
	int_price GetPriceAdjustment() const noexcept;

private:
	//! Items needed for the recipe.
	items mItems;
	//! Doubloon cost for the recipe.
	count mDoubloonCount;
	//! Items generated by the recipe.
	count mYield;
	//! Price adjustment for the recipe to use when computing order price.
	int_price mPriceAdjustment;
};

} // ypp_sm namespace
